development:
  adapter: mysql2
  database: question_api_development
  user: root
  password:  

test: &test
  adapter: mysql2
  database: question_api_test
  user: root
  password:

production:
  adapter: mysql2
  database: question_api_production
  user: root
  password: f1Zzg00d

cucumber:
  <<: *test